name: Export Size Comment
on:
  pull_request:
    branches:
      - main

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: antfu/export-size-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths: package/zhead
